import type { ApiProduct } from '~/utils/catalog'

/**
 * The brand's real catalogue (26 slipper styles and 2 shoes) mirrored from
 * `backend/database/data/products.json`, which is what the API seeds.
 *
 * The listing and the product detail page fall back to this when the API
 * returns nothing, and the cart drawer and "you may also like" row read it
 * directly, so it has to be the same products the API serves: a demo sandal
 * here would be recommended next to real ones.
 *
 * Names, prices, size ranges, materials and departments are the client's own
 * (30 Sep 2026). There is deliberately no description, rating, review or cost
 * breakdown: the client supplied none, and the detail page hides those
 * sections when the fields are absent. `size_availability` is a placeholder
 * count, not real stock; the API is the source of truth for that.
 *
 * Keep the name `DESIGN_PRODUCTS`: several files import it.
 */
export const DESIGN_PRODUCTS: ApiProduct[] = [
  {
    slug: 'abrantie',
    name: 'Abrantie Collection',
    base_price_ghs: 50000,
    images: [
      '/products/abrantie/1-black.webp',
      '/products/abrantie/2-black.webp',
      '/products/abrantie/3-blue.webp',
      '/products/abrantie/4-tan.webp',
    ],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Blue', hex: '#1E4C8F' },
      { name: 'Tan', hex: '#B8732E' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Foam board', 'Bona', 'Welt'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'adomba',
    name: 'Adomba Collection',
    base_price_ghs: 50000,
    images: ['/products/adomba/1-tan.webp', '/products/adomba/2-black.webp'],
    color: 'Tan',
    colors: [
      { name: 'Tan', hex: '#B8732E' },
      { name: 'Black', hex: '#000000' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Bona', 'Soft leather'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'agudie',
    name: 'Agudie Collection',
    base_price_ghs: 50000,
    images: ['/products/agudie/1-red.webp', '/products/agudie/2-white.webp'],
    color: 'Red',
    colors: [
      { name: 'Red', hex: '#C6212B' },
      { name: 'White', hex: '#FFFFFF' },
    ],
    product_type: 'slippers',
    departments: ['mens', 'womens'],
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Macro', 'Welt'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 36: 5, 37: 5, 38: 5, 39: 5, 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'ahoofe',
    name: 'Ahoɔfɛ Collection',
    base_price_ghs: 50000,
    images: ['/products/ahoofe/1-black.webp'],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Foam board', 'Buckle', 'Macro', 'Welt'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'asantewaa',
    name: 'Asantewaa Collection',
    base_price_ghs: 30000,
    images: ['/products/asantewaa/1-red.webp'],
    color: 'Red',
    colors: [
      { name: 'Red', hex: '#C6212B' },
    ],
    product_type: 'slippers',
    departments: ['womens'],
    sizes: ['36', '37', '38', '39', '40', '41', '42'],
    materials: ['Velvet fabric', 'Bona', 'Foam board'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 36: 5, 37: 5, 38: 5, 39: 5, 40: 5, 41: 5, 42: 5 },
  },
  {
    slug: 'aseda',
    name: 'Aseda Collection',
    base_price_ghs: 50000,
    images: ['/products/aseda/1-black.webp', '/products/aseda/2-brown.webp'],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Brown', hex: '#5A3A22' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Velvet fabric', 'Soft leather', 'Bona', 'Macro', 'Foam board'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'atwerebor',
    name: 'Atwerebor Collection',
    base_price_ghs: 50000,
    images: [
      '/products/atwerebor/1-black.webp',
      '/products/atwerebor/2-brown.webp',
    ],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Brown', hex: '#5A3A22' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Macro', 'Foam board'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'awia',
    name: 'Awia Collection',
    base_price_ghs: 50000,
    images: ['/products/awia/1-black.webp'],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Buckle', 'Macro', 'Welt'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'awuraba',
    name: 'Awuraba Collection',
    base_price_ghs: 30000,
    images: ['/products/awuraba/1-black.webp', '/products/awuraba/2-navy.webp'],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Navy', hex: '#1B2A4A' },
    ],
    product_type: 'slippers',
    departments: ['womens'],
    sizes: ['36', '37', '38', '39', '40', '41', '42'],
    materials: ['Velvet fabric', 'Soft fabric', 'Bona', 'Foam board'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 36: 5, 37: 5, 38: 5, 39: 5, 40: 5, 41: 5, 42: 5 },
  },
  {
    slug: 'besiwaa',
    name: 'Besiwaa Collection',
    base_price_ghs: 30000,
    images: ['/products/besiwaa/1-black.webp'],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
    ],
    product_type: 'slippers',
    departments: ['womens'],
    sizes: ['36', '37', '38', '39', '40', '41', '42'],
    materials: ['Foam board', 'Soft leather', 'Buckle', 'Bona', 'Welt'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 36: 5, 37: 5, 38: 5, 39: 5, 40: 5, 41: 5, 42: 5 },
  },
  {
    slug: 'danso',
    name: 'Danso Collection',
    base_price_ghs: 50000,
    images: ['/products/danso/1-blue.webp'],
    color: 'Blue',
    colors: [
      { name: 'Blue', hex: '#1E4C8F' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Foam board', 'Bona', 'Welt', 'Macro'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'domfo',
    name: 'Domfo Collection',
    base_price_ghs: 50000,
    images: [
      '/products/domfo/1-tan.webp',
      '/products/domfo/2-green.webp',
      '/products/domfo/3-blue.webp',
      '/products/domfo/4-black.webp',
    ],
    color: 'Tan',
    colors: [
      { name: 'Tan', hex: '#B8732E' },
      { name: 'Green', hex: '#2F4A3A' },
      { name: 'Blue', hex: '#1E4C8F' },
      { name: 'Black', hex: '#000000' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Foam board', 'Bona'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'gyata',
    name: 'Gyata Collection',
    base_price_ghs: 50000,
    images: ['/products/gyata/1-tan.webp'],
    color: 'Tan',
    colors: [
      { name: 'Tan', hex: '#B8732E' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Suede fabric', 'Bona', 'Macro', 'Foam board', 'Welt'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'kania',
    name: 'Kania Collection',
    base_price_ghs: 50000,
    images: [
      '/products/kania/1-black.webp',
      '/products/kania/2-tan.webp',
      '/products/kania/3-blue.webp',
    ],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Tan', hex: '#B8732E' },
      { name: 'Blue', hex: '#1E4C8F' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Foam board', 'Bona', 'Macro', 'Eyelet'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'nanaba',
    name: 'Nanaba Collection',
    base_price_ghs: 50000,
    images: [
      '/products/nanaba/1-black.webp',
      '/products/nanaba/2-blue.webp',
      '/products/nanaba/3-brown.webp',
    ],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Blue', hex: '#1E4C8F' },
      { name: 'Brown', hex: '#5A3A22' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Foam board'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'nimdea',
    name: 'Nimdea Collection',
    base_price_ghs: 50000,
    images: ['/products/nimdea/1-black.webp'],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Foam board', 'Macro', 'Welt'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'nshira',
    name: 'Nshira Collection',
    base_price_ghs: 50000,
    images: [
      '/products/nshira/1-brown.webp',
      '/products/nshira/2-black.webp',
      '/products/nshira/3-black.webp',
    ],
    color: 'Brown',
    colors: [
      { name: 'Brown', hex: '#5A3A22' },
      { name: 'Black', hex: '#000000' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Foam board', 'Macro', 'Welt'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'nyarko',
    name: 'Nyarko Collection',
    base_price_ghs: 50000,
    images: [
      '/products/nyarko/1-tan.webp',
      '/products/nyarko/2-brown.webp',
      '/products/nyarko/3-black.webp',
    ],
    color: 'Tan',
    colors: [
      { name: 'Tan', hex: '#B8732E' },
      { name: 'Brown', hex: '#5A3A22' },
      { name: 'Black', hex: '#000000' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Foam board', 'Macro', 'Welt'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'obaapa',
    name: 'Obaapa Collection',
    base_price_ghs: 30000,
    images: [
      '/products/obaapa/1-blue.webp',
      '/products/obaapa/2-black.webp',
      '/products/obaapa/3-purple.webp',
    ],
    color: 'Blue',
    colors: [
      { name: 'Blue', hex: '#1E4C8F' },
      { name: 'Black', hex: '#000000' },
      { name: 'Purple', hex: '#3B1F5B' },
    ],
    product_type: 'slippers',
    departments: ['womens'],
    sizes: ['36', '37', '38', '39', '40', '41', '42'],
    materials: ['Soft fabric', 'Bona', 'Foam board', 'Velvet fabric'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 36: 5, 37: 5, 38: 5, 39: 5, 40: 5, 41: 5, 42: 5 },
  },
  {
    slug: 'odehyieba',
    name: 'Odehyieba Collection',
    base_price_ghs: 50000,
    images: [
      '/products/odehyieba/1-tan.webp',
      '/products/odehyieba/2-white.webp',
      '/products/odehyieba/3-black.webp',
    ],
    color: 'Tan',
    colors: [
      { name: 'Tan', hex: '#B8732E' },
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Black', hex: '#000000' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Foam board', 'Welt', 'Macro'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'odeneho',
    name: 'Odeneho Collection',
    base_price_ghs: 50000,
    images: [
      '/products/odeneho/1-tan.webp',
      '/products/odeneho/2-black.webp',
      '/products/odeneho/3-black.webp',
      '/products/odeneho/4-blue.webp',
      '/products/odeneho/5-green.webp',
    ],
    color: 'Tan',
    colors: [
      { name: 'Tan', hex: '#B8732E' },
      { name: 'Black', hex: '#000000' },
      { name: 'Blue', hex: '#1E4C8F' },
      { name: 'Green', hex: '#2F4A3A' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Foam board', 'Welt', 'Macro'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'ogya',
    name: 'Ogya Collection',
    base_price_ghs: 50000,
    images: ['/products/ogya/1-black.webp', '/products/ogya/2-black.webp'],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Foam board', 'Welt', 'Macro'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'ohene',
    name: 'Ohene Collection',
    base_price_ghs: 60000,
    images: ['/products/ohene/1-white.webp'],
    color: 'White',
    colors: [
      { name: 'White', hex: '#FFFFFF' },
    ],
    product_type: 'slippers',
    departments: ['mens', 'womens'],
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
    materials: ['Bona', 'Foam board', 'Macro', 'Soft leather', 'Adinkra symbol'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 36: 5, 37: 5, 38: 5, 39: 5, 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'okatakyie',
    name: 'Okatakyie Collection',
    base_price_ghs: 50000,
    images: [
      '/products/okatakyie/1-black.webp',
      '/products/okatakyie/2-navy.webp',
      '/products/okatakyie/3-brown.webp',
    ],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Navy', hex: '#1B2A4A' },
      { name: 'Brown', hex: '#5A3A22' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Foam board', 'Welt', 'Macro'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'opanyin',
    name: 'Opanyin Collection',
    base_price_ghs: 50000,
    images: [
      '/products/opanyin/1-black.webp',
      '/products/opanyin/2-green.webp',
    ],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Green', hex: '#2F4A3A' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Foam board', 'Welt', 'Velvet fabric', 'Macro'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'wofa',
    name: 'Wofa Collection',
    base_price_ghs: 50000,
    images: ['/products/wofa/1-black.webp', '/products/wofa/2-navy.webp'],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Navy', hex: '#1B2A4A' },
    ],
    product_type: 'slippers',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Bona', 'Foam board', 'Macro', 'Soft leather'],
    category: { name: 'Slippers', slug: 'slippers' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'krakye',
    name: 'Krakye Collection',
    base_price_ghs: 70000,
    images: ['/products/krakye/1-black.webp', '/products/krakye/2-navy.webp'],
    color: 'Black',
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Navy', hex: '#1B2A4A' },
    ],
    product_type: 'closed-toe',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Lace', 'Welt'],
    category: { name: 'Shoes', slug: 'shoes' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
  {
    slug: 'osram',
    name: 'Osram Collection',
    base_price_ghs: 70000,
    images: [
      '/products/osram/1-tan.webp',
      '/products/osram/2-black.webp',
      '/products/osram/3-brown.webp',
    ],
    color: 'Tan',
    colors: [
      { name: 'Tan', hex: '#B8732E' },
      { name: 'Black', hex: '#000000' },
      { name: 'Brown', hex: '#5A3A22' },
    ],
    product_type: 'closed-toe',
    departments: ['mens'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    materials: ['Soft leather', 'Bona', 'Foam board', 'Welt', 'Macro'],
    category: { name: 'Shoes', slug: 'shoes' },
    size_availability: { 40: 5, 41: 5, 42: 5, 43: 5, 44: 5, 45: 5 },
  },
]
